export const SPECIAL_AWARDS: { key: string; title: string; suffix: string }[] = [
  { key: "golden_boot", title: "🥇 Golden Boot", suffix: "Goals" },
  { key: "playmaker", title: "🅰️ Playmaker", suffix: "Assists" },
  { key: "golden_glove", title: "🧤 Golden Glove", suffix: "Clean Sheets" },
  { key: "best_gk", title: "👑 Best Goalkeeper", suffix: "Pts" },
  { key: "best_def", title: "🛡️ Best Defenders", suffix: "Pts" },
  { key: "best_mid", title: "🎩 Best Midfielders", suffix: "Pts" },
  { key: "best_fwd", title: "💥 Best Forwards", suffix: "Pts" },
  { key: "best_vc", title: "🥈 Best Vice-Captain", suffix: "Pts" },
  { key: "transfer_king", title: "🔀 Transfer King", suffix: "Pts" },
  { key: "bench_king", title: "🪑 Bench King", suffix: "Pts" },
  { key: "dream_team", title: "🌟 Dream Team King", suffix: "DT Score" },
  { key: "shooting_stars", title: "🌠 Shooting Stars", suffix: "Rank Rise" },
  { key: "defensive_king", title: "🧱 Defensive King", suffix: "Contribution" },
  { key: "penalty_king", title: "🎯 Penalty King", suffix: "Pts" },
  { key: "highest_gw_score", title: "🚀 Highest GW Score", suffix: "Pts" },
  { key: "freehit_king", title: "🃏 Free Hit King", suffix: "Pts" },
  { key: "benchboost_king", title: "📈 Bench Boost King", suffix: "Pts" },
  { key: "triplecaptain_king", title: "©️³ Triple Captain King", suffix: "Pts" },
  { key: "expects_king", title: "🔮 Expects King", suffix: "xGI" },
  { key: "hardworking_af", title: "💪 Hardworking AF", suffix: "Mins" },
  { key: "half_season_first", title: "🌗 Half Season Wonders (H1)", suffix: "Pts" },
  { key: "half_season_second", title: "🌓 Half Season Wonders (H2)", suffix: "Pts" },
  { key: "bad_luck_h2h", title: "😢 Bad Luck H2H", suffix: "GW Streak" },
  { key: "reversed_motw", title: "🔻 Reversed MotW", suffix: "Times Lowest" },
];
